FROM ubuntu:22.04

ENV URL=https://github.com/atsign-foundation/noports.git
ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/app/output

ARG branch=trunk

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    apt-get update ; \
    apt-get install -y git python3-pip ; \
    cd ${REPO_DIR} ; \
    git clone ${URL} . ; \
    git checkout ${branch} ; \
    pip3 install cmake==3.24.0 ; \
    cd ${REPO_DIR}/packages/c/sshnpd ; cmake -S . -B build ; cmake --build build ; \
    mv ./build/at_activate ${OUTPUT_DIR}/at_activate ; \
    mv ./build/sshnpd ${OUTPUT_DIR}/sshnpd ; \
    mv ./build/libsshnpd-lib.a ${OUTPUT_DIR}/libsshnpd-lib.a ; \
    cd ${REPO_DIR}/packages/c/srv ; \
    cmake -S . -B build -DATAUTH_BUILD_EXECUTABLES=OFF ; \
    cmake --build build ; \
    mv build/srv ${OUTPUT_DIR}/srv
