FROM debian:stable-slim@sha256:5484adc33b4c352c5a9f4c4ae295fc49aed1cb54a7a0712a1b29674fb6f4f10f AS buildimage

ENV URL="https://api.github.com/repos/atsign-foundation/noports/releases/latest"
ENV URLP="https://github.com/atsign-foundation/noports/releases/download"
ENV BUILD_DIR=/app
ENV OUTPUT_DIR=/output

ARG release=latest

RUN apt-get update && \
    apt-get install -y wget dpkg curl && \
    mkdir -p ${BUILD_DIR} ${OUTPUT_DIR} && \
    cd ${BUILD_DIR} && \
    case "$(dpkg --print-architecture)" in \
    amd64) ARCH="x64";; \
    armhf) ARCH="arm";; \
    arm64) ARCH="arm64";; \
    riscv64) ARCH="riscv64";; \
    esac && \
    if [ -z ${release} ] || [ "${release}" = 'latest' ]; then \
        LATEST_VERSION=$(curl --silent ${URL} | grep -Po '"tag_name": "\Kv.*?(?=")') && \
        VERSION=${LATEST_VERSION}; \
    else \
        VERSION=${release}; \
    fi && \
    wget "${URLP}/${VERSION}/sshnp-linux-${ARCH}.tgz" && \
    tar -xvf sshnp-linux-${ARCH}.tgz && \
    rm sshnp-linux-${ARCH}.tgz && \
    cd sshnp && \
    mv -f at_activate install.sh np_admin npp_atserver npp_file npt srv srvd sshnp sshnpd ${OUTPUT_DIR} || true

FROM debian:stable-slim@sha256:5484adc33b4c352c5a9f4c4ae295fc49aed1cb54a7a0712a1b29674fb6f4f10f AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

RUN set -eux ; \
    apt-get update ; \
    apt-get install -y openssh-server sudo; \
    groupadd --gid ${GROUP_ID} ${USER} ; \
    useradd --system --shell /bin/bash --home ${HOMEDIR} --uid ${USER_ID} --gid ${GROUP_ID} ${USER} ; \
    usermod -aG sudo ${USER} ; \
    mkdir -p ${HOMEDIR}/.ssh ${HOMEDIR}/.atsign/keys ; \
    touch ${HOMEDIR}/.ssh/authorized_keys ; \
    ssh-keygen -t ed25519 -a 100 -f ${HOMEDIR}/.ssh/id_ed25519 -q -N '' ; \
    cat ${HOMEDIR}/.ssh/id_ed25519.pub >> ${HOMEDIR}/.ssh/authorized_keys ; \
    chmod 700 ${HOMEDIR}/.ssh ; \
    chmod 644 ${HOMEDIR}/.ssh/authorized_keys ; \
    chmod 600 ${HOMEDIR}/.ssh/id_ed25519 ; \
    chmod 644 ${HOMEDIR}/.ssh/id_ed25519.pub ; \
    sed -i '$ a %sudo ALL=(ALL:ALL) NOPASSWD:ALL' /etc/sudoers ; \
    sed -E -i 's|^#?(PasswordAuthentication)\s.*|\1 no|' /etc/ssh/sshd_config ; \
    sed -i 's/#ListenAddress 0.0.0.0/ListenAddress localhost/g' /etc/ssh/sshd_config ; \
    chown -R ${USER}:${USER} ${HOMEDIR} ;

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start

