FROM dart:3.7.0@sha256:1daa53cdfd134254c7a40958ff238a3a1348d4ad999544b292e43602bd19379f AS buildimage

ENV URL=https://github.com/atsign-foundation/noports.git
ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/usr/local/bin
ENV PACKAGE_DIR=${REPO_DIR}/packages/dart/sshnoports

ARG branch=trunk

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    apt-get update ; \
    apt-get install -y git ; \
    cd ${REPO_DIR} ; \
    git clone ${URL} . ; \
    git checkout ${branch} ; \
    dart pub get -C ${PACKAGE_DIR} ; \
    dart compile exe ${PACKAGE_DIR}/bin/activate_cli.dart -o ${OUTPUT_DIR}/at_activate ; \
    dart compile exe ${PACKAGE_DIR}/bin/npp_atserver.dart -o ${OUTPUT_DIR}/npp_atserver ; \
    dart compile exe ${PACKAGE_DIR}/bin/npp_file.dart -o ${OUTPUT_DIR}/npp_file ; \
    dart compile exe ${PACKAGE_DIR}/bin/npt.dart -o ${OUTPUT_DIR}/npt ; \
    dart compile exe ${PACKAGE_DIR}/bin/sshnp.dart -o ${OUTPUT_DIR}/sshnp ; \
    dart compile exe ${PACKAGE_DIR}/bin/sshnpd.dart -o ${OUTPUT_DIR}/sshnpd ; \
    dart compile exe ${PACKAGE_DIR}/bin/srv.dart -o ${OUTPUT_DIR}/srv ; \
    dart compile exe ${PACKAGE_DIR}/bin/srvd.dart -o ${OUTPUT_DIR}/srvd

FROM debian:stable-slim@sha256:5484adc33b4c352c5a9f4c4ae295fc49aed1cb54a7a0712a1b29674fb6f4f10f AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /usr/local/bin/at_activate /usr/local/bin/at_activate
COPY --from=buildimage /usr/local/bin/npp_atserver /usr/local/bin/npp_atserver
COPY --from=buildimage /usr/local/bin/npp_file /usr/local/bin/npp_file
COPY --from=buildimage /usr/local/bin/npt /usr/local/bin/npt
COPY --from=buildimage /usr/local/bin/sshnp /usr/local/bin/sshnp
COPY --from=buildimage /usr/local/bin/sshnpd /usr/local/bin/sshnpd
COPY --from=buildimage /usr/local/bin/srv /usr/local/bin/srv
COPY --from=buildimage /usr/local/bin/srvd /usr/local/bin/srvd

RUN set -eux ; \
    apt-get update ; \
    apt-get install -y openssh-server sudo vim nano iproute2 nmap tmux curl cron ; \
    groupadd --gid ${GROUP_ID} ${USER} ; \
    useradd --system --shell /bin/bash --home ${HOMEDIR} --uid ${USER_ID} --gid ${GROUP_ID} ${USER} ; \
    usermod -aG sudo ${USER} ; \
    mkdir -p ${HOMEDIR}/.ssh ${HOMEDIR}/.atsign/keys ; \
    chown -R ${USER}:${USER} ${HOMEDIR} ; \
    touch ${HOMEDIR}/.ssh/authorized_keys ; 

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
