name: e2e_all

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - trunk

  pull_request:
    paths-ignore:
      - "docs/**"
    branches:
      - trunk
      - release-v*.*.*

jobs:
  e2e_all:
    # Don't run on PRs from a fork or Dependabot as the secrets aren't available
    if:
      ${{ github.event.pull_request.head.repo.fork == false && github.actor !=
      'dependabot[bot]'}}
    concurrency: e2e_all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
      - name: Run e2e_all main.sh
        run: |
          mkdir -p /tmp/e2e_all          
          mkdir -p ~/.atsign/keys/
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > ~/.atsign/keys/@8incanteater_key.atKeys
          echo "${{ secrets.ATKEYS_8485WEALTHY51 }}" > ~/.atsign/keys/@8485wealthy51_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > ~/.atsign/keys/@8052simple_key.atKeys
          echo "${{ secrets.ATKEYS_829SNOWSHOEING }}" > ~/.atsign/keys/@829snowshoeing_key.atKeys
          echo "Test started at: $(date)"
          start_time=$(date +%s)          
          tests/e2e_all/scripts/main.sh @8incanteater @8485wealthy51 @rv_am -u atsign -p
          test_exit_code=$?
          end_time=$(date +%s)
          echo "Test finished at: $(date)"
          echo "Total execution time: $((end_time - start_time)) seconds"          
          exit $test_exit_code

    # steps:
    #   - name: execute tests on cicd vm
    #     uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f # v1.2.2
    #     env:
    #       SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    #     with:
    #       host: ${{ secrets.NOPORTS_CICD_HOST }}
    #       username: ubuntu
    #       key: ${{ secrets.NOPORTS_CICD_SSH_KEY }}
    #       envs: SHA
    #       command_timeout: 15m
    #       script: |
    #         cd noports
    #         rm -rf tests/e2e_all/runtime
    #         mkdir -p tests/e2e_all/runtime
    #         echo "Running git fetch"
    #         git fetch
    #         echo "Running git checkout -f $SHA"
    #         git checkout -f "$SHA"
    #         echo "Running tests"
    #         tests/e2e_all/scripts/main.sh @apricoteventual @combinedbelgian @rv_am -u atsign -p
    #         sudo docker image prune -f # prune dangling images
