name: npm build test

on:
  workflow_dispatch:
  pull_request:
    branches: [trunk]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  npm-build-test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: npm build test
        working-directory: apps/admin/webapp
        run: npm run build
