name: npm build test

on:
  workflow_dispatch:
  pull_request:
    branches: [trunk]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  npm-build-test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node-version
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: '20.17.0'
      - name: setup required npm version and test build
        working-directory: ./apps/admin/webapp
        run: |
          npm ci npm@10.8.2
          npm ci
          npm run build
